// root layout for all pages
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import 'bootstrap/dist/css/bootstrap.min.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Media Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,

}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
        <Header></Header>
        <main>
          { children }
        </main>
      </body>
    </html>
  )
}
